# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Add or remove bower_components from the exclusion list 
# in order for jekyll to detect/ignore the associated dependencies

exclude:
  - node_modules
  - resources
  - README.md
baseurl: /taboga

# Development base url 
# site:
#   url:
#     - http://192.168.10.10:4000/

# Github Pages base url
site:
  url:
    - taboga